export default [
  {
    type: "女性 A",
    img: require("../../images/model/images (1).jpg"),
    fituser: "21岁",
    price: "3000",
    paymethod: "",
    billing: "",
    features: ["时尚 C"],
  },
  {
    type: "女性 Z",
    img: require("../../images/model/images (4).jpg"),
    fituser: "24岁",
    price: "5000",
    paymethod: "per user per month, billed annually",
    billing: "US$8 billed monthly",
    features: ["时尚 T"],
  },
  {
    type: "女性 M",
    img: require("../../images/model/images (5).jpg"),
    fituser: "24岁",
    price: "8000",
    paymethod: "per user per month, billed annually",
    billing: "US$8 billed monthly",
    features: ["时尚 M"],
  },
  {
    type: "女性 K",
    img: require("../../images/model/images (6).jpg"),
    fituser: "24岁",
    price: "12000",
    paymethod: "per user per month, billed annually",
    billing: "US$8 billed monthly",
    features: ["时尚 O"],
  },
  // {
  //   type: "女性 U",
  //   img: require("../../images/model/images (7).jpg"),
  //   fituser: "24岁",
  //   price: 3000,
  //   paymethod: "per user per month, billed annually",
  //   billing: "US$8 billed monthly",
  //   features: ["时尚 W"],
  // },
  // {
  //   type: "女性 R",
  //   img: require("../../images/model/images (8).jpg"),
  //   fituser: "24岁",
  //   price: "3000",
  //   paymethod: "per user per month, billed annually",
  //   billing: "US$8 billed monthly",
  //   features: ["时尚 C"],
  // },
  // {
  //   type: "女性 Q",
  //   img: require("../../images/model/images (9).jpg"),
  //   fituser: "24岁",
  //   price: "12000",
  //   paymethod: "per user per month, billed annually",
  //   billing: "US$8 billed monthly",
  //   features: ["时尚 I"],
  // },
];
